train_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: "../data_preparation/imagenet/dataset/fgsm/train/adv"
      root_path_2: "../data_preparation/imagenet/dataset/fgsm/train/clean"
      repeat: 20
      cache: 'none' #in_memory
  wrapper:
    name: sr-implicit-paired-adv
    args:
      inp_size: 48
      augment: true
  batch_size: 64

val_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: "../data_preparation/imagenet/dataset/fgsm/val/adv" 
      root_path_2: "../data_preparation/imagenet/dataset/fgsm/val/clean"
      first_k: 10
      repeat: 160
      cache: 'none' #in_memory
  wrapper:
    name: sr-implicit-paired-adv
    args:
      inp_size: 48
  batch_size: 256

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: liif
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: true
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256, 256, 256, 256]


optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 3
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 1
epoch_save: 1

# for latent space regularization
L2_reg:
   flag: False
   weight: 0
gram_reg:
   flag: False
   weight: 0

